name: scala-CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    name: ソースコードのフォーマット確認
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}

      - name: Check formatting
        run: sbt scalafmtCheckAll

  test-all:
    name: B4プロセッサのテスト
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup nix
        uses: cachix/install-nix-action@v23

      - name: setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: pineapplehunter

      - name: test all
        run: make check

#      - name: generate processor
#        run: make processor
#
#      - name: upload processor source as artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: processor
#          path: processor/*
